ALTER TABLE configuracao ADD COLUMN IF NOT EXISTS aluguel_mensal NUMERIC(10,2) DEFAULT 0;
ALTER TABLE configuracao ADD COLUMN IF NOT EXISTS funcionarios_mensal NUMERIC(10,2) DEFAULT 0;
ALTER TABLE configuracao ADD COLUMN IF NOT EXISTS energia_mensal NUMERIC(10,2) DEFAULT 0;
ALTER TABLE configuracao ADD COLUMN IF NOT EXISTS agua_mensal NUMERIC(10,2) DEFAULT 0;
ALTER TABLE configuracao ADD COLUMN IF NOT EXISTS outros_fixos NUMERIC(10,2) DEFAULT 0;
ALTER TABLE configuracao ADD COLUMN IF NOT EXISTS tolerancia_caixa NUMERIC(10,2) DEFAULT 10;
